### ISSUE TITLE
Test failed on Windows

### ISSUE THREAD

**Issue by jinq0123** [lileio/lile#27]
```
D:/Go/bin/go.exe test -v [E:/gopath/src/github.com/jinq0123/users/server]
panic: listen unix /tmp/008531f5-cf69-11e7-a9eb-00ff198f3a8c: socket: An address incompatible with the requested protocol was used.

goroutine 1 [running]:
github.com/lileio/lile.NewTestServer(0xc042020c00, 0x0, 0x0, 0xc042020c00)
	e:/gopath/src/github.com/lileio/lile/lile.go:147 +0x1bb
github.com/jinq0123/users/server.TestMain(0xc04206bf18)
	e:/gopath/src/github.com/jinq0123/users/server/server_test.go:24 +0x73
main.main()
	github.com/jinq0123/users/server/_test/_testmain.go:44 +0xe2
exit status 2
FAIL	github.com/jinq0123/users/server	1.097s
```

**Comment by arbarlow** [comment]
Unfortunately I have no access to a windows machine to try this, are you able to provide a patch? It will be the test server creating a unix based socket I suspect.

**Comment by arbarlow** [comment]
unfortunately closing due to my lack of windows availability, though I'm very happy to take a PR
